---
# This playbook deploys the whole application stack in this site.  

- name: deploy to dmt server
  hosts: test-site
  remote_user: jseddon

  vars_files:
    - vars/prima-dm-site

  roles:
    - app
    - server
